# Lab 1 Part I: MNIST 2D CNN

## Imports

In [1]:
import numpy as np
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Input, Conv2D, MaxPool2D, Flatten, Dense
from keras.datasets import mnist
from keras.utils.np_utils import to_categorical

## Load and format MNIST dataset

In [2]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = x_train.astype('float32') / 255
x_test  = x_test.astype('float32')  / 255
x_train = x_train.reshape((60000, 28, 28, 1)) # 'channels_last' format
x_test  = x_test.reshape((10000, 28, 28, 1)) # 'channels_last' format
y_train = to_categorical(y_train, 10)
y_test  = to_categorical(y_test,  10)

## Build model

In [3]:
model = Sequential()
model.add(Input(shape=(28, 28, 1)))
model.add(Conv2D(filters=10, kernel_size=(3, 3), activation='relu'))
model.add(MaxPool2D())
model.add(Conv2D(filters=10, kernel_size=(7, 7), activation='relu'))
model.add(Flatten())
model.add(Dense(units=10, activation='softmax'))
model.summary()
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 26, 26, 10)        100       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 13, 13, 10)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 7, 7, 10)          4910      
                                                                 
 flatten (Flatten)           (None, 490)               0         
                                                                 
 dense (Dense)               (None, 10)                4910      
                                                                 
Total params: 9,920
Trainable params: 9,920
Non-trainable params: 0
______________________________________________________

## Train model

In [4]:
model.fit(x_train, y_train, epochs=5, validation_data=(x_test, y_test))

Epoch 1/5
1875/1875 [==============================] - 13s 7ms/step - loss: 0.2322 - categorical_accuracy: 0.9315 - val_loss: 0.0811 - val_categorical_accuracy: 0.9759
Epoch 2/5
1875/1875 [==============================] - 12s 7ms/step - loss: 0.0759 - categorical_accuracy: 0.9772 - val_loss: 0.0514 - val_categorical_accuracy: 0.9836
Epoch 3/5
1875/1875 [==============================] - 12s 6ms/step - loss: 0.0549 - categorical_accuracy: 0.9832 - val_loss: 0.0513 - val_categorical_accuracy: 0.9820
Epoch 4/5
1875/1875 [==============================] - 12s 6ms/step - loss: 0.0454 - categorical_accuracy: 0.9861 - val_loss: 0.0405 - val_categorical_accuracy: 0.9870
Epoch 5/5
1875/1875 [==============================] - 12s 6ms/step - loss: 0.0376 - categorical_accuracy: 0.9885 - val_loss: 0.0447 - val_categorical_accuracy: 0.9851


## Evaluate model

In [5]:
model.evaluate(x_test, y_test, verbose=2)
pred_test = model.predict(x_test)
print(tf.math.confusion_matrix(y_test.argmax(axis=1), pred_test.argmax(axis=1)))

313/313 - 1s - loss: 0.0447 - categorical_accuracy: 0.9851 - 1s/epoch - 4ms/step
313/313 [==============================] - 1s 3ms/step
tf.Tensor(
[[ 976    0    0    0    0    0    1    0    1    2]
 [   0 1128    0    4    0    1    0    1    1    0]
 [   2    2 1015    5    1    0    0    4    2    1]
 [   0    0    0 1007    0    2    0    0    0    1]
 [   1    1    1    0  956    0    2    1    0   20]
 [   1    0    0   11    0  875    1    0    0    4]
 [   4    2    0    1    1    1  946    0    2    1]
 [   0    1    6    6    0    0    0  999    1   15]
 [   6    0    2    5    0    4    1    2  947    7]
 [   0    0    0    2    2    1    0    2    0 1002]], shape=(10, 10), dtype=int32)


## Save trained model

In [6]:
model.save('lab1_part1_mnist.h5')