# Lab 1 Part I: MNIST 2D CNN

## Imports

In [ ]:
import numpy as np
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Input, Conv2D, MaxPool2D, Flatten, Dense
from keras.datasets import mnist
from keras.utils.np_utils import to_categorical

## Load and format MNIST dataset

In [6]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = x_train.astype('float32') / 255
x_test  = x_test.astype('float32')  / 255
x_train = x_train.reshape((60000, 28, 28, 1)) # 'channels_last' format
x_test  = x_test.reshape((10000, 28, 28, 1)) # 'channels_last' format
y_train = to_categorical(y_train, 10)
y_test  = to_categorical(y_test,  10)

## Build model

In [7]:
model = Sequential()
model.add(Input(shape=(28, 28, 1)))
model.add(Conv2D(filters=8, kernel_size=(3, 3), activation='relu'))
model.add(MaxPool2D())
model.add(Conv2D(filters=8, kernel_size=(7, 7), activation='relu'))
model.add(Flatten())
model.add(Dense(units=10, activation='softmax'))
model.summary()
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_2 (Conv2D)           (None, 26, 26, 8)         80        
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 13, 13, 8)        0         
 2D)                                                             
                                                                 
 conv2d_3 (Conv2D)           (None, 7, 7, 8)           3144      
                                                                 
 flatten_1 (Flatten)         (None, 392)               0         
                                                                 
 dense_1 (Dense)             (None, 10)                3930      
                                                                 
Total params: 7,154
Trainable params: 7,154
Non-trainable params: 0
____________________________________________________

## Train model

In [8]:
model.fit(x_train, y_train, epochs=8, validation_data=(x_test, y_test))

Epoch 1/8
1875/1875 [==============================] - 19s 10ms/step - loss: 0.2649 - categorical_accuracy: 0.9211 - val_loss: 0.1014 - val_categorical_accuracy: 0.9680
Epoch 2/8
1875/1875 [==============================] - 20s 11ms/step - loss: 0.0964 - categorical_accuracy: 0.9703 - val_loss: 0.0680 - val_categorical_accuracy: 0.9785
Epoch 3/8
1875/1875 [==============================] - 23s 12ms/step - loss: 0.0711 - categorical_accuracy: 0.9781 - val_loss: 0.0535 - val_categorical_accuracy: 0.9816
Epoch 4/8
1875/1875 [==============================] - 25s 13ms/step - loss: 0.0574 - categorical_accuracy: 0.9822 - val_loss: 0.0487 - val_categorical_accuracy: 0.9837
Epoch 5/8
1875/1875 [==============================] - 20s 11ms/step - loss: 0.0484 - categorical_accuracy: 0.9848 - val_loss: 0.0477 - val_categorical_accuracy: 0.9849
Epoch 6/8
1875/1875 [==============================] - 25s 13ms/step - loss: 0.0425 - categorical_accuracy: 0.9866 - val_loss: 0.0457 - val_categorical_acc

## Evaluate model

In [9]:
model.evaluate(x_test, y_test, verbose=2)
pred_test = model.predict(x_test)
print(tf.math.confusion_matrix(y_test.argmax(axis=1), pred_test.argmax(axis=1)))

313/313 - 2s - loss: 0.0472 - categorical_accuracy: 0.9857 - 2s/epoch - 7ms/step
313/313 [==============================] - 2s 5ms/step
tf.Tensor(
[[ 968    1    1    0    0    2    2    2    4    0]
 [   0 1122    3    3    1    0    1    2    3    0]
 [   1    0 1028    0    0    0    0    2    1    0]
 [   0    0    5 1000    0    2    0    1    2    0]
 [   0    0    3    0  970    0    2    0    2    5]
 [   0    0    1   10    0  876    1    0    1    3]
 [   6    1    2    0    1    2  944    0    2    0]
 [   0    1   11    2    0    0    0 1009    1    4]
 [   1    0    7    3    1    3    0    2  951    6]
 [   2    0    1    5    4    3    0    2    3  989]], shape=(10, 10), dtype=int32)


## Save trained model

In [6]:
model.save('lab1_part1_mnist.h5')